"""v1.x comparison (PLAN D.7–D.9) → reports/v1x_comparison.md

D.7 / H8: do simple food rankings build good diets?  (greedy diets; LP restricted to a metric's top-k foods;
          Maillot-2008-style check: are LP-selected foods in the top quartile of simple metrics?)
D.8 / H3: cross-profile summary (from the optimizer)
D.9     : typical diets vs the owner's targets, and the smallest change that makes each one meet them
"""
import sys
from dataclasses import replace
from pathlib import Path

import numpy as np
import pandas as pd
import yaml

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from src import metrics as M  # noqa: E402
from src import optimizer as O  # noqa: E402
from src.analysis.explore import md_table  # noqa: E402
from src.targets import load_profile  # noqa: E402

OUT = ROOT / "reports/v1x_comparison.md"
PROFILES = {p.stem: p for p in sorted((ROOT / "config/profiles").glob("*.yaml"))}
SIMPLE = {"kcal_per_eur": "calories per €", "protein_per_eur": "protein per €",
          "useful_protein_per_eur": "useful protein per €", "useful_protein_per_1000kcal": "useful protein per kcal",
          "carb_per_eur": "carbohydrate per €"}


def evaluate(t, g, s):
    """Nutrient totals, target misses and cost of a diet given as grams eaten (Series indexed by food_id)."""
    g = g.reindex(t.index).fillna(0)
    tot = {k: float((t[k] * g).sum()) for k in ["kcal", "protein", "carb", "fat", "free_sugars", "fibre"]}
    foods = pd.DataFrame({"g_eaten": g[g > 0]})
    aa = O.aa_adequacy(t, foods, s.protein)
    miss = []
    if tot["protein"] < s.protein * 0.98:
        miss.append(f"protein {tot['protein']:.0f}/{s.protein:.0f} g")
    if s.carb_lo and tot["carb"] < s.carb_lo * 0.98:
        miss.append(f"carb {tot['carb']:.0f} < {s.carb_lo:.0f} g")
    if s.carb_hi and tot["carb"] > s.carb_hi * 1.02:
        miss.append(f"carb {tot['carb']:.0f} > {s.carb_hi:.0f} g")
    if tot["fat"] < s.fat_lo * 0.98:
        miss.append(f"fat {tot['fat'] * 9 / tot['kcal']:.0%} E < 20 %")
    if tot["fat"] > s.fat_hi * 1.02:
        miss.append(f"fat {tot['fat'] * 9 / tot['kcal']:.0%} E > 35 %")
    if tot["free_sugars"] > s.free_sugars_max * 1.02:
        miss.append(f"free sugars {tot['free_sugars']:.0f} > {s.free_sugars_max:.0f} g")
    if aa.min() < 0.98:
        miss.append(f"{aa.idxmin()} adequacy {aa.min():.2f}")
    if abs(tot["kcal"] / s.energy - 1) > 0.05:
        miss.append(f"energy {tot['kcal']:,.0f}/{s.energy:,.0f} kcal")
    return {**tot, "cost": float((t.eur * g).sum()), "mass": float(g.sum()), "lowest_aa": f"{aa.idxmin()} {aa.min():.2f}",
            "misses": "; ".join(miss) or "none"}


def greedy(t, s, metric_values):
    """Fill the energy target by taking foods in metric order (each up to its cap and the 30 % energy share)."""
    g = pd.Series(0.0, index=t.index)
    left = s.energy
    for f in metric_values.sort_values(ascending=False).index:
        if f not in t.index or left <= 0 or t.kcal[f] <= 0:
            continue
        take = min(t.cap[f], s.max_share * s.energy / t.kcal[f], left / t.kcal[f])
        g[f] = take
        left -= take * t.kcal[f]
    return g


def main():
    s, _ = O.spec_from_profile(load_profile(PROFILES["owner"]))
    t = O.food_table()
    master = M.load().set_index("food_id")
    core_ids = [f for f in t.index if t.role[f] == "core"]
    opt = O.solve(t, s)
    L = ["# v1.x comparison (generated by `src/analysis/comparison.py`)\n\n",
         f"Owner targets: {s.energy:,.0f} kcal, protein ≥ {s.protein:.0f} g, carbohydrate {s.carb_lo:.0f}–{s.carb_hi:.0f} g, "
         f"fat {s.fat_lo:.0f}–{s.fat_hi:.0f} g, free sugars ≤ {s.free_sugars_max:.0f} g, all amino acids. "
         f"Optimizer (minimum cost): **€{opt.cost_eur:.2f}/day**, {opt.mass_g:,.0f} g.\n\n"]

    # ---------------- D.7a greedy diets from one simple ranking
    rows = []
    for m, lab in SIMPLE.items():
        g = greedy(t, s, master.loc[core_ids, m])
        e = evaluate(t, g, s)
        rows.append({"diet built from the ranking": lab, "cost €": e["cost"], "mass g": e["mass"], "kcal": e["kcal"],
                     "protein g": e["protein"], "targets missed": e["misses"]})
    rows.append({"diet built from the ranking": "**optimizer (for comparison)**", "cost €": opt.cost_eur, "mass g": opt.mass_g,
                 "kcal": opt.totals.set_index("nutrient").diet.kcal, "protein g": opt.totals.set_index("nutrient").diet.protein,
                 "targets missed": "none"})
    L += ["## D.7 / H8: can a simple ranking build a good diet?\n\n### a) Greedy diet: take the best-ranked foods "
          "(each ≤ its cap and ≤ 30 % of energy) until the energy target is reached\n\n", md_table(pd.DataFrame(rows), 1)]

    # ---------------- D.7b LP restricted to top-k of a simple metric
    rows = []
    for m, lab in SIMPLE.items():
        r = {"metric": lab}
        for k in (10, 15, 20, 30):
            top = master.loc[core_ids, m].nlargest(k).index.tolist()
            ing = [f for f in t.index if t.role[f] == "ingredient"]
            sol = O.solve(t.loc[top + ing], s)
            r[f"top {k}"] = f"+{(sol.cost_eur / opt.cost_eur - 1) * 100:.0f} %" if sol.status == "optimal" else "infeasible"
        rows.append(r)
    L += ["\n### b) Optimizer allowed to use only the top-k foods of one simple ranking (+ cooking ingredients): "
          "extra cost vs the full optimizer\n\n", md_table(pd.DataFrame(rows))]

    # ---------------- D.7c Maillot-style: are LP-chosen foods top-quartile on simple metrics?
    chosen = set()
    for k, path in PROFILES.items():
        sp, _ = O.spec_from_profile(load_profile(path))
        if sp.objective == "cost":
            chosen |= {f for f in O.solve(t, sp).foods.index if t.role[f] == "core"}
    rows = []
    for m, lab in SIMPLE.items():
        q = master.loc[core_ids, m].rank(pct=True)
        rows.append({"metric": lab, "LP-chosen foods in top quartile": f"{(q.reindex(list(chosen)) >= 0.75).mean():.0%}",
                     "all core foods in top quartile": "25 %"})
    L += [f"\n### c) Foods chosen by the minimum-cost optimizer for any profile ({len(chosen)} core foods: "
          f"{', '.join(sorted(t.name[list(chosen)]))}) vs simple rankings\n\n", md_table(pd.DataFrame(rows)),
          "\nCompare Maillot et al. 2008: 81 % of LP-selected foods had good nutrient-quality-for-price vs 39 % of others.\n"]

    # ---------------- D.9 typical diets
    tmpl = yaml.safe_load(open(ROOT / "config/diet_templates.yaml"))
    tt = O.food_table(roles=["core", "ingredient", "snack"])
    L.append("\n## D.9 Typical diets vs the owner's targets\n\n")
    rows = []
    for key, d in tmpl.items():
        g = pd.Series(d["foods"], dtype=float)
        e = evaluate(tt, g, s)
        rows.append({"diet": d["label"], "kcal": e["kcal"], "protein g": e["protein"], "carb g": e["carb"],
                     "fat % E": 100 * 9 * e["fat"] / e["kcal"], "free sugars g": e["free_sugars"], "fibre g": e["fibre"],
                     "mass g": e["mass"], "cost €/day": e["cost"], "targets missed": e["misses"]})
    L += [md_table(pd.DataFrame(rows), 1), "\n"]
    L.append("### Smallest change that makes each diet meet every target\n\n")
    for key, d in tmpl.items():
        g = pd.Series(d["foods"], dtype=float)
        usual = evaluate(tt, g, s)
        sol = O.closest_diet(tt, s, g)
        sol2 = O.closest_diet(tt, s, g, max_cost=usual["cost"])
        L.append(f"**{d['label']}** (now €{usual['cost']:.2f}/day)\n\n")
        if sol.status != "optimal":
            L.append("No feasible adjustment. Conflicts: " + ", ".join(sol.conflicts.constraint) + "\n\n")
            continue
        ch = sol.changes.copy()
        ch = ch.assign(usual_g=ch.usual_g.round(0), new_g=ch.new_g.round(0), change_g=ch.change_g.round(0))
        L += [md_table(ch[["name", "usual_g", "new_g", "change_g"]].reset_index(drop=True), 0),
              f"\nAdjusted diet: €{sol.cost_eur:.2f}/day, {sol.mass_g:,.0f} g. Same change but not more expensive than now: "
              + (f"€{sol2.cost_eur:.2f}/day ({len(sol2.changes)} foods changed)" if sol2.status == "optimal" else "not possible")
              + "\n\n"]

    # ---------------- D.8 / H3 summary pointer
    L.append("## D.8 / H3: profiles\n\nSee `reports/v1.0_optimizer.md` §1 and `reports/scenarios_v0.2.md`: optimal food sets "
             "differ by goal mainly through protein density (fat loss → lean animal foods and dairy) and the "
             "price-insensitive objective (→ compact foods); all cost-minimizing profiles share the legume + grain core.\n")
    OUT.write_text("".join(L))
    print(OUT.read_text())


if __name__ == "__main__":
    main()
