"""v0.1 exploratory analysis (PLAN A.6–A.7) → reports/v0.1_exploration.md (+ figures/v0.1/*.png).

Scope: core foods (role == core) with a price and composition. Ingredients, snacks and supplements are
excluded here (PROJECT.md §9.1, safeguard 5). Results are descriptive; hypotheses are checked, not proven.
"""
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import StandardScaler

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from src import metrics as M  # noqa: E402

OUT = ROOT / "reports/v0.1_exploration.md"
FIG = ROOT / "figures/v0.1"
PCA_COLS = ["kcal_100g_eaten", "useful_protein_100g_eaten", "carb_100g_eaten", "fat_energy_pct", "kcal_per_eur",
            "useful_protein_per_eur", "diaas"]  # g/1000 kcal omitted: it is 1/(energy density)
LOG_COLS = {"kcal_100g_eaten", "kcal_per_eur", "useful_protein_per_eur", "g_eaten_per_1000kcal",
            "useful_protein_100g_eaten", "carb_100g_eaten"}


def md_table(df, floatfmt=1):
    df = df.copy()
    for c in df.columns:
        if pd.api.types.is_float_dtype(df[c]):
            df[c] = df[c].map(lambda v: "" if pd.isna(v) else f"{v:.{floatfmt}f}")
    head = "| " + " | ".join(map(str, df.columns)) + " |\n|" + "---|" * len(df.columns) + "\n"
    return head + "\n".join("| " + " | ".join(map(str, r)) + " |" for r in df.astype(str).values) + "\n"


def core_foods():
    df = M.load()
    core = df[(df.role == "core") & df.eur_per_kg_edible.notna() & df.kcal_100g_purchased.notna()].copy()
    return df, core.set_index("food_id")


def main():
    FIG.mkdir(parents=True, exist_ok=True)
    df, c = core_foods()
    L = [f"# v0.1 exploration: {len(c)} core foods (generated by `src/analysis/explore.py`)\n",
         "Data: `data/processed/foods_master.csv` (prices 2026-10-06: CSP 12-month means + Cenu Depo snapshot). "
         "Useful protein = protein × min(DIAAS, 100)/100 (adult pattern) unless stated. **Descriptive results, "
         "not recommendations**: no constraints, no diet context (that is v1.0).\n"]

    # ---------------- A.6 descriptive statistics by group
    g = c.groupby("group").agg(n=("name_en", "size"), kcal_100g=("kcal_100g_eaten", "median"),
                               useful_prot_100g=("useful_protein_100g_eaten", "median"),
                               diaas=("diaas", "median"), eur_kg=("eur_per_kg_edible", "median"),
                               kcal_per_eur=("kcal_per_eur", "median"),
                               useful_prot_per_eur=("useful_protein_per_eur", "median"),
                               g_per_1000kcal=("g_eaten_per_1000kcal", "median"))
    L += ["## 1. Medians by food group\n", md_table(g.reset_index())]

    # ---------------- leaders per metric
    L.append("## 2. Top 5 per metric\n")
    for col in ["kcal_per_eur", "useful_protein_per_eur", "carb_per_eur", "useful_protein_100g_eaten",
                "kcal_100g_eaten", "useful_protein_per_1000kcal", "g_eaten_per_1000kcal"]:
        hib = M.METRICS[col][2]
        top = c[col].sort_values(ascending=not hib).head(5)
        L.append(f"- **{M.METRICS[col][0]}** ({M.METRICS[col][1]}): " +
                 ", ".join(f"{c.loc[i, 'name_en']} {v:,.1f}" for i, v in top.items()) + "\n")

    # ---------------- Pareto fronts
    L.append("\n## 3. Pareto fronts (foods no other core food beats on both axes)\n")
    pairs = [("useful_protein_100g_eaten", "kcal_100g_eaten"), ("useful_protein_per_eur", "kcal_per_eur"),
             ("useful_protein_per_eur", "carb_per_eur"), ("useful_protein_per_1000kcal", "kcal_per_eur"),
             ("kcal_per_eur", "g_eaten_per_1000kcal")]
    for a, b in pairs:
        fr = M.front(c, [a, b]).sort_values(a)
        L.append(f"- {M.METRICS[a][0]} × {M.METRICS[b][0]}: " + ", ".join(fr.name_en) + "\n")
    four = ["kcal_per_eur", "useful_protein_per_eur", "kcal_100g_eaten", "g_eaten_per_1000kcal"]
    c["pareto_rank_4d"] = M.pareto_ranks(c[four].to_numpy(), [M.METRICS[x][2] for x in four])
    L.append(f"- 4-D front ({', '.join(M.METRICS[x][0] for x in four)}): "
             + ", ".join(c[c.pareto_rank_4d == 1].name_en) + "\n")

    # ---------------- A.7 hypothesis checks via ranking comparisons
    L.append("\n## 4. Hypothesis checks (rank comparisons; Spearman ρ and top-10 overlap)\n")
    crude = M.with_quality(df, "crude").set_index("food_id").loc[c.index]
    child = M.with_quality(df, "diaas_child").set_index("food_id").loc[c.index]
    checks = [
        ("H1 quality adjustment (protein/€)", crude.useful_protein_per_eur, c.useful_protein_per_eur),
        ("H1 quality adjustment (protein/100 g)", crude.useful_protein_100g_eaten, c.useful_protein_100g_eaten),
        ("D10 adult vs child pattern (protein/€)", c.useful_protein_per_eur, child.useful_protein_per_eur),
        ("H2 price (protein: density vs per €)", c.useful_protein_100g_eaten, c.useful_protein_per_eur),
        ("H2 price (energy: density vs per €)", c.kcal_100g_eaten, c.kcal_per_eur),
        ("H5 mass vs cost (low g/1000 kcal vs high kcal/€)", -c.g_eaten_per_1000kcal, c.kcal_per_eur),
    ]
    rows = []
    for name, a, b in checks:
        r = M.compare_rankings(a, b, 10)
        rows.append({"comparison": name, "spearman_rho": r["spearman"], "top10_overlap": r["top10_overlap"],
                     "n": r["n"]})
    L.append(md_table(pd.DataFrame(rows), 2))
    moved = (c.useful_protein_per_eur.rank(ascending=False) - crude.useful_protein_per_eur.rank(ascending=False))
    biggest = moved.abs().sort_values(ascending=False).head(6)
    L.append("\nLargest rank changes from quality adjustment (protein/€; + = drops that many places, − = rises): " +
             ", ".join(f"{c.loc[i, 'name_en']} {moved[i]:+.0f}" for i in biggest.index) + "\n")
    # H4: who owns the top-10s
    L.append("\n**H4: share of the top 10 by group**\n\n")
    share = {}
    for col in ["kcal_per_eur", "useful_protein_per_eur", "useful_protein_100g_eaten", "useful_protein_per_1000kcal"]:
        share[M.METRICS[col][0]] = c.nlargest(10, col).group.value_counts()
    L.append(md_table(pd.DataFrame(share).fillna(0).astype(int).reset_index().rename(columns={"index": "group"})))

    # ---------------- correlations, PCA, clustering
    X = c[PCA_COLS].copy()
    for col in LOG_COLS & set(X.columns):
        X[col] = np.log10(X[col].clip(lower=1e-3))
    X = X.dropna()
    corr = X.corr(method="spearman")
    L.append("\n## 5. Spearman correlations between metrics (core foods)\n\n")
    L.append(md_table(corr.reset_index().rename(columns={"index": "metric"}), 2))
    Z = StandardScaler().fit_transform(X)
    pca = PCA().fit(Z)
    load = pd.DataFrame(pca.components_[:3].T, index=X.columns, columns=["PC1", "PC2", "PC3"])
    L.append(f"\n## 6. PCA (standardized; log for skewed metrics)\n\nExplained variance: "
             + ", ".join(f"PC{i + 1} {v:.0%}" for i, v in enumerate(pca.explained_variance_ratio_[:4])) + "\n\n")
    L.append(md_table(load.reset_index().rename(columns={"index": "metric"}), 2))
    scores = pca.transform(Z)[:, :2]
    best = max(range(3, 8), key=lambda k: silhouette_score(Z, KMeans(k, n_init=20, random_state=0).fit_predict(Z)))
    lab = KMeans(best, n_init=20, random_state=0).fit_predict(Z)
    L.append(f"\n## 7. k-means clusters (k = {best}, chosen by silhouette over 3–7)\n\n")
    for k in range(best):
        members = X.index[lab == k]
        L.append(f"- **Cluster {k + 1}** ({len(members)}): " + ", ".join(c.loc[members, "name_en"]) + "\n")
    c.loc[X.index, "cluster"] = lab + 1
    c.loc[X.index, "pc1"], c.loc[X.index, "pc2"] = scores[:, 0], scores[:, 1]
    c.reset_index().to_csv(ROOT / "data/processed/v0.1_exploration_foods.csv", index=False, float_format="%.4g")

    L.append("\n## 8. Caveats\n- Prices: CSP (official means) and Cenu Depo (≈10 % lower on cross-checked foods) are mixed; "
             "a price-source sensitivity run is planned (PLAN D.1).\n- Grade C digestibility proxies (fish, nuts, buckwheat, …) "
             "and grade C composition (stewed meat, curd snack, pelmeņi) are included; see `foods_master.csv` grades.\n"
             "- Food-level 'useful protein' ignores complementarity between foods; diet-level amino-acid constraints come "
             "in v1.0 (decision D9).\n")
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("".join(L))
    print(OUT.read_text()[:6000])


if __name__ == "__main__":
    main()
