"""v1.0 optimizer results → reports/v1.0_optimizer.md + figures/v1.0/*.png (PLAN C, H5/H6/H9/H10/H11, D.4)."""
import sys
from dataclasses import replace
from pathlib import Path

import matplotlib
import numpy as np
import pandas as pd

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from src import optimizer as O  # noqa: E402
from src import plots as P  # noqa: E402
from src.analysis.explore import md_table  # noqa: E402
from src.targets import load_profile  # noqa: E402

OUT = ROOT / "reports/v1.0_optimizer.md"
FIG = ROOT / "figures/v1.0"
PROFILES = {p.stem: p for p in sorted((ROOT / "config/profiles").glob("*.yaml"))}


def diet_md(sol):
    f = sol.foods.copy()
    f["share"] = (f.energy_share * 100).round(0).astype(int).astype(str) + " %"
    f = f[["name", "g_eaten", "g_bought", "cost_eur", "kcal_total", "protein_total", "carb_total", "fat_total", "share"]]
    f.columns = ["food", "g eaten", "g bought", "€", "kcal", "protein g", "carb g", "fat g", "energy share"]
    return md_table(f.reset_index(drop=True), 1)


def totals_line(sol):
    t = sol.totals.set_index("nutrient").diet
    return (f"**Total:** {t.kcal:,.0f} kcal · protein {t.protein:.0f} g · carbohydrate {t.carb:.0f} g · fat {t.fat:.0f} g "
            f"({t.fat * 9 / t.kcal:.0%} E) · fibre {t.fibre:.0f} g · food mass {sol.mass_g:,.0f} g eaten · "
            f"**cost €{sol.cost_eur:.2f}/day**\n")


def main():
    FIG.mkdir(parents=True, exist_ok=True)
    t = O.food_table()
    L = ["# v1.0 diet optimizer results (generated by `src/analysis/optimize_report.py`)\n\n",
         f"Linear programme over {len(t)} foods (core + cooking ingredients, priced). Targets from `src/targets.py`; "
         "safeguards from `config/optimizer.yaml`; protein quality enforced per amino acid (decision D9). Prices: "
         "Latvia 2026-10-06. **These are minimum-cost (or minimum-mass) solutions, i.e. a lower bound and a "
         "map of trade-offs, not meal plans**: taste, fibre, micronutrients and variety beyond the safeguards come "
         "in v2.0.\n\n"]

    # ---------------- per profile
    L.append("## 1. Optimal daily diet per profile\n\n")
    summary, groups = [], {}
    owner_spec = None
    for k, path in PROFILES.items():
        prof = load_profile(path)
        s, r = O.spec_from_profile(prof)
        sol = O.solve(t, s)
        if k == "owner":
            owner_spec, owner_sol = s, sol
        L.append(f"### {prof.name} (objective: {s.objective})\n\n")
        if sol.status != "optimal":
            L.append("Infeasible. Conflicting targets:\n\n" + md_table(sol.conflicts, 2) + "\n")
            continue
        L += [diet_md(sol), "\n", totals_line(sol)]
        aa = O.aa_adequacy(t, sol.foods, s.protein)
        L.append(f"Amino-acid adequacy (supplied ÷ required): lowest {aa.idxmin()} {aa.min():.2f}\n\n")
        if len(sol.binding):
            b = sol.binding[~sol.binding.constraint.str.startswith("energy share")].head(5)
            L.append("Binding constraints (objective change per unit tighter): " +
                     "; ".join(f"{r.constraint} {r.objective_per_unit_tighter:.4f}" for r in b.itertuples()) + "\n\n")
        summary.append({"profile": prof.name, "kcal target": s.energy, "protein target g": s.protein,
                        "cost €/day": sol.cost_eur, "food mass g": sol.mass_g, "foods": len(sol.foods),
                        "animal-food energy %": 100 * sol.foods[sol.foods.group.isin(["Meat & fish", "Eggs & dairy"])].energy_share.sum()})
        groups[prof.name.split("(")[0].split(",")[0].strip()] = sol.foods.groupby("group").energy_share.sum()
    L += ["### Summary\n\n", md_table(pd.DataFrame(summary), 1), "\n"]

    # stacked bar: energy share by group per profile
    G = pd.DataFrame(groups).fillna(0).T
    fig, ax = plt.subplots(figsize=(10, 5.5))
    fig.subplots_adjust(left=0.22, right=0.75, top=0.84, bottom=0.18)
    left = np.zeros(len(G))
    for g in [g for g in P.COLORS if g in G.columns]:
        ax.barh(G.index, G[g] * 100, left=left, color=P.COLORS[g], edgecolor="white", linewidth=1.5, label=g, height=0.6)
        left += G[g].to_numpy() * 100
    P._style(ax, "Where the energy comes from in each optimal diet",
             "Minimum-cost diet per profile (professional: minimum food mass). Share of daily energy by food group.",
             "% of daily energy", "")
    ax.set_xlim(0, 100)
    ax.legend(loc="upper left", bbox_to_anchor=(1.02, 1), frameon=True, edgecolor="black", fancybox=False, fontsize=9)
    fig.savefig(FIG / "1_energy_by_group.png", dpi=150)
    plt.close(fig)
    L.append("![energy by group](../figures/v1.0/1_energy_by_group.png)\n\n")

    # ---------------- H11: safeguards
    s = owner_spec
    L.append("## 2. H11: what the safeguards do (owner profile, minimum cost)\n\n")
    rows = []
    for sg in ["none", "macros", "full"]:
        sol = O.solve(t, replace(s, safeguards=sg))
        top = sol.foods.head(3)
        rows.append({"safeguards": sg, "cost €/day": sol.cost_eur, "mass g": sol.mass_g, "foods": len(sol.foods),
                     "fat % E": 100 * 9 * sol.totals.set_index("nutrient").diet.fat / sol.totals.set_index("nutrient").diet.kcal,
                     "largest contributors": ", ".join(f"{n} {e:.0%}" for n, e in zip(top.name, top.energy_share))})
    L += [md_table(pd.DataFrame(rows), 1), "\n`none` = energy + protein + amino acids only; `macros` adds carbohydrate band, "
          "fat 20–35 % E and the free-sugar cap; `full` adds per-food caps and ≤ 30 % of energy per food.\n\n"]

    # ---------------- H9: protein constraint formulation
    L.append("## 3. H9: how protein quality is enforced changes the diet (owner, minimum cost)\n\n")
    rows = []
    for mode, label in [("aa", "per amino acid, diet level (D9)"), ("pq", "Σ protein × DIAAS, food level"),
                        ("crude", "crude protein only")]:
        sol = O.solve(t, replace(s, protein_mode=mode))
        aa = O.aa_adequacy(t, sol.foods, s.protein)
        rows.append({"protein constraint": label, "cost €/day": sol.cost_eur, "protein g": sol.totals.set_index("nutrient").diet.protein,
                     "lowest AA adequacy": f"{aa.idxmin()} {aa.min():.2f}", "foods": ", ".join(sol.foods.name.head(5))})
    L += [md_table(pd.DataFrame(rows), 2),
          "\nAdequacy < 1.00 means the diet does not supply that amino acid at the reference-protein level for the "
          "protein target. Food-level Σ P×DIAAS ignores complementarity between foods and over-constrains the diet; "
          "crude protein under-constrains it.\n\n"]

    # ---------------- H5/H6: cost vs mass Pareto front
    fr = O.cost_mass_front(t, s, 10)
    L += ["## 4. H5: cost vs food mass (owner): ε-constraint Pareto front\n\n", md_table(fr, 2), "\n"]
    fig, ax = plt.subplots(figsize=(9, 6))
    fig.subplots_adjust(left=0.12, right=0.95, top=0.84, bottom=0.14)
    ax.plot(fr.mass_g, fr.cost_eur, color="#2a78d6", lw=2, marker="o", ms=7, mec="black", mew=0.6, zorder=3)
    for (i, dx, dy, ha) in [(0, 12, -18, "left"), (len(fr) // 2, 0, 22, "center"), (len(fr) - 1, -6, 22, "right")]:
        r = fr.iloc[i]
        ax.annotate(f"€{r.cost_eur:.2f}, {r.mass_g:,.0f} g\n{r.main_foods}", (r.mass_g, r.cost_eur), xytext=(dx, dy),
                    textcoords="offset points", fontsize=8.5, ha=ha, va="center")
    ax.set_ylim(0, fr.cost_eur.max() * 1.1)
    P._style(ax, "Cheaper or more compact? The trade-off for one day of food",
             "Owner targets (3,300 kcal, 137 g protein, carbohydrate band, amino acids, safeguards). Each point is an optimal diet.",
             "Food eaten per day (g)", "Cost per day (€)")
    fig.savefig(FIG / "2_cost_vs_mass.png", dpi=150)
    plt.close(fig)
    L.append("![cost vs mass](../figures/v1.0/2_cost_vs_mass.png)\n\n")

    # ---------------- C.9 alternatives + D.4 safeguard sensitivity
    base = O.solve(t, s)
    L += ["## 5. Near-optimal alternatives (ban one main food, re-optimize)\n\n", md_table(O.alternatives(t, s, base, 5), 2), "\n"]
    rows = []
    for share in [0.2, 0.3, 0.5]:
        for tol in [0.02]:
            sol = O.solve(t, replace(s, max_share=share))
            rows.append({"max energy share per food": share, "cost €/day": sol.cost_eur, "foods": len(sol.foods),
                         "top foods": ", ".join(sol.foods.name.head(4))})
    O.CFG["max_g_eaten"]["category"]["legumes"] = 300
    t2 = O.food_table()
    sol = O.solve(t2, s)
    rows.append({"max energy share per food": "0.3 + legumes ≤ 300 g", "cost €/day": sol.cost_eur, "foods": len(sol.foods),
                 "top foods": ", ".join(sol.foods.name.head(4))})
    L += ["## 6. Sensitivity to judgment-call safeguards (owner, minimum cost)\n\n", md_table(pd.DataFrame(rows), 2), "\n"]
    OUT.write_text("".join(L))
    print(OUT.read_text())


if __name__ == "__main__":
    main()
