"""Scenario comparison of food rankings across profiles (v0.2 check) → reports/scenarios_v0.2.md + figure.

A. Same weighting preset for every profile        → does the person change the ranking?
B. Each profile with its goal's default preset    → what a user of that profile would actually see
C. Owner profile: protein-quality × price scenario → robustness of one person's ranking
"""
import itertools
import sys
from pathlib import Path

import matplotlib
import numpy as np
import pandas as pd

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from src import export as X  # noqa: E402
from src import metrics as M  # noqa: E402
from src.analysis.explore import md_table  # noqa: E402
from src.targets import RULES, load_profile  # noqa: E402

PROFILES = {p.stem: p for p in sorted((ROOT / "config/profiles").glob("*.yaml"))}
OUT = ROOT / "reports/scenarios_v0.2.md"
FIG = ROOT / "figures/v0.2"


def ranking(profile, preset, quality="diaas", price="central"):
    out, _, _ = X.build(profile, preset, ("core",), quality, price)
    return out.set_index("food_id")[["rank", "score", "food"]]


def compare(a, b, k=10):
    j = a[["score"]].join(b[["score"]], lsuffix="_a", rsuffix="_b", how="inner")
    rho = j.score_a.rank().corr(j.score_b.rank())
    ta, tb = set(a.nsmallest(k, "rank").index), set(b.nsmallest(k, "rank").index)
    return rho, len(ta & tb) / k


def heatmap(mat, labels, path, title, subtitle):
    fig, ax = plt.subplots(figsize=(8.5, 7))
    fig.subplots_adjust(left=0.27, right=0.93, top=0.83, bottom=0.22)
    im = ax.imshow(mat, cmap="Blues", vmin=0, vmax=1)
    ax.set_xticks(range(len(labels)), labels, rotation=40, ha="right", fontsize=9)
    ax.set_yticks(range(len(labels)), labels, fontsize=9)
    for i, j in itertools.product(range(len(labels)), repeat=2):
        v = mat[i, j]
        ax.text(j, i, f"{v:.2f}", ha="center", va="center", fontsize=9, color="white" if v > 0.6 else "black")
    for s in ax.spines.values():
        s.set_color("black")
    ax.tick_params(direction="in", colors="black")
    cb = fig.colorbar(im, ax=ax, fraction=0.046, pad=0.03)
    cb.set_label("Spearman rank correlation of composite scores", fontsize=9)
    fig.text(0.04, 0.96, title, fontsize=13, weight="bold", va="top")
    fig.text(0.04, 0.915, subtitle, fontsize=9.5, color="#333333", va="top")
    fig.savefig(path, dpi=150, facecolor="white")
    plt.close(fig)


def main():
    FIG.mkdir(parents=True, exist_ok=True)
    names = {k: load_profile(v).name for k, v in PROFILES.items()}
    goal_preset = {k: RULES["presets"][load_profile(v).goal]["ranking_preset"] for k, v in PROFILES.items()}
    L = ["# Scenario comparison of food rankings (v0.2)\n\n",
         "Generated by `src/analysis/scenarios.py`. Core foods only (ingredients/snacks/supplements excluded). "
         "Ranking = composite score (weighted geometric mean of percentile-normalized metrics, `src/metrics.py`).\n\n"]

    # ---------------- A: same preset for everyone
    preset = "Bulking: balanced"
    A = {k: ranking(v, preset) for k, v in PROFILES.items()}
    base = A["owner"]
    rows = [{"profile": names[k], "spearman vs owner": compare(base, r)[0], "top-10 overlap vs owner": compare(base, r)[1]}
            for k, r in A.items()]
    L += [f"## A. Same preset ('{preset}') for every profile\n\n", md_table(pd.DataFrame(rows), 2),
          "\n**Reading:** food-level rankings use only food properties, the weighting, the protein-quality definition "
          "and prices. The person's targets (kcal, protein g) do not enter a single-food score, so every profile gets "
          "the same list, except a profile with `priorities.cost = 0`, for which all per-€ weights are dropped. "
          "Person-specific choices come from the diet optimizer (v1.0), where targets are constraints.\n\n"]

    # ---------------- B: goal-default preset per profile
    B = {k: ranking(v, goal_preset[k]) for k, v in PROFILES.items()}
    keys = list(PROFILES)
    top = pd.DataFrame({f"{names[k].split('(')[0].strip()}\n[{goal_preset[k]}]":
                        B[k].nsmallest(10, "rank").food.tolist() for k in keys}, index=range(1, 11))
    L += ["## B. Each profile with its goal's default ranking preset\n\n",
          "| profile | goal | ranking preset |\n|---|---|---|\n" +
          "".join(f"| {names[k]} | {RULES['presets'][load_profile(PROFILES[k]).goal]['label']} | {goal_preset[k]} |\n"
                  for k in keys), "\n### Top 10 per profile\n\n"]
    L.append(md_table(top.rename(columns=lambda c: c.replace("\n", " ")).reset_index().rename(columns={"index": "rank"})))
    n = len(keys)
    rho = np.ones((n, n))
    ov = np.ones((n, n))
    for i, j in itertools.combinations(range(n), 2):
        r, o = compare(B[keys[i]], B[keys[j]])
        rho[i, j] = rho[j, i] = r
        ov[i, j] = ov[j, i] = o
    short = [names[k].split("(")[0].split(",")[0].strip() for k in keys]
    L += ["\n### Pairwise agreement (Spearman ρ of scores / top-10 overlap)\n\n",
          md_table(pd.DataFrame(rho, index=short, columns=short).round(2).reset_index().rename(columns={"index": ""}), 2),
          "\n", md_table(pd.DataFrame(ov, index=short, columns=short).round(1).reset_index().rename(columns={"index": ""}), 1)]
    # foods that are top-10 for exactly one profile
    tops = {k: set(B[k].nsmallest(10, "rank").index) for k in keys}
    allf = B[keys[0]].food.to_dict()
    L.append("\n### Foods in the top 10 of only one profile\n\n")
    for k in keys:
        only = tops[k] - set().union(*(tops[x] for x in keys if x != k))
        L.append(f"- **{short[keys.index(k)]}**: " + (", ".join(allf.get(f, f) for f in sorted(only)) or "none") + "\n")
    common = set.intersection(*tops.values())
    L.append(f"- **In every profile's top 10:** {', '.join(allf.get(f, f) for f in common) or 'none'}\n")
    heatmap(rho, short, FIG / "scenario_rank_agreement.png", "How similar are the food rankings between profiles?",
            "Each profile ranked with its goal's default preset; 1 = identical order, 0 = unrelated.")
    L.append("\n![rank agreement](../figures/v0.2/scenario_rank_agreement.png)\n")

    # ---------------- C: robustness of the owner's ranking
    p = goal_preset["owner"]
    baseC = ranking(PROFILES["owner"], p)
    rows = []
    for q in M.QUALITY:
        for pr in M.PRICE_SCENARIOS:
            r = ranking(PROFILES["owner"], p, q, pr)
            rh, o = compare(baseC, r)
            new = set(r.nsmallest(10, "rank").index) - set(baseC.nsmallest(10, "rank").index)
            rows.append({"protein quality": q, "price scenario": pr, "spearman vs default": rh,
                         "top-10 overlap": o, "new in top 10": ", ".join(allf.get(f, f) for f in sorted(new))})
    L += [f"\n## C. Robustness of the owner's ranking ('{p}')\n\n", md_table(pd.DataFrame(rows), 2)]

    # ---------------- D: normalization sensitivity for each goal preset
    df = M.load()
    core = df[(df.role == "core") & df.eur_per_kg_edible.notna()].set_index("food_id")
    rows = []
    for pr in dict.fromkeys(goal_preset.values()):
        s = {m: M.composite(core, M.PRESETS[pr], m) for m in M.NORMALIZATIONS}
        for a_, b_ in itertools.combinations(M.NORMALIZATIONS, 2):
            ta, tb = set(s[a_].nlargest(10).index), set(s[b_].nlargest(10).index)
            rows.append({"preset": pr, "methods": f"{a_} vs {b_}", "spearman": s[a_].rank().corr(s[b_].rank()),
                         "top-10 overlap": len(ta & tb) / 10})
    L += ["\n## D. Sensitivity to the normalization method (same preset, same foods)\n\n", md_table(pd.DataFrame(rows), 2),
          "\n**Reading:** composite scores depend noticeably on how metrics are put on a common scale. "
          "Log-ratio scales stretch near-zero values (e.g. fruit with almost no protein), percentile ranks discard "
          "magnitudes, linear min-max is dominated by one extreme food. Composite rankings are therefore a convenience "
          "view; Pareto fronts and the v1.0 optimizer (targets as constraints, no weighting of incommensurable "
          "metrics) are the primary results (PROJECT.md §2, §4).\n"]
    OUT.write_text("".join(L))
    print(OUT.read_text())


if __name__ == "__main__":
    main()
