"""v2.0 results (PLAN E.1–E.7) → reports/v2.0_nutrients.md"""
import sys
from dataclasses import replace
from pathlib import Path

import pandas as pd
import yaml

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
from src import optimizer as O  # noqa: E402
from src.analysis.explore import md_table  # noqa: E402
from src.targets import compute, load_profile  # noqa: E402

OUT = ROOT / "reports/v2.0_nutrients.md"
PROFILES = {p.stem: p for p in sorted((ROOT / "config/profiles").glob("*.yaml"))}


def adequacy(sol, res):
    rows = []
    for k, m in res.micros.items():
        v = sol.micro_totals.get(O.MICRO_COL.get(k, k), float("nan"))
        rows.append({"key": k, "nutrient": m.label, "value": v, "min": m.min, "max": m.max, "enforce": m.enforce,
                     "pct_of_min": 100 * v / m.min if m.min else None})
    return pd.DataFrame(rows)


def main():
    t = O.food_table()
    L = ["# v2.0: vitamins, minerals, fibre, sodium, saturated fat (generated by `src/analysis/v2_report.py`)\n\n",
         "EFSA adult reference values (`config/micronutrients.yaml`); cooking losses from USDA raw↔cooked pairs "
         "(true-retention method). v1.0 = energy, protein, amino acids, macros and safeguards only.\n\n"]
    rows, gaps = [], []
    for k, path in PROFILES.items():
        prof = load_profile(path)
        res = compute(prof)
        s, _ = O.spec_from_profile(prof)
        v1, v2 = O.solve(t, replace(s, use_micros=False)), O.solve(t, s)
        name = prof.name.split("(")[0].split(",")[0].strip()
        added = sorted(set(v2.foods.name) - set(v1.foods.name)) if v2.status == "optimal" else []
        rows.append({"profile": name, "objective": s.objective, "v1.0 €/day": v1.cost_eur,
                     "v2.0 €/day": v2.cost_eur if v2.status == "optimal" else None, "v2.0 mass g": v2.mass_g,
                     "foods added by v2.0": ", ".join(added),
                     "binding nutrients": ", ".join(b.split(" (")[0] for b in v2.binding.constraint
                                                    if not b.startswith(("energy", "amino", "protein", "fat (", "carbohydrate")))
                     if v2.status == "optimal" and len(v2.binding) else ""})
        a = adequacy(v1, res)
        short = a[a.enforce & a["min"].notna() & (a.value < a["min"] * 0.99)]
        over = a[a.enforce & a["max"].notna() & (a.value > a["max"] * 1.01)]
        gaps.append({"profile": name, "v1.0 diet below minimum": ", ".join(f"{r.nutrient} {r.pct_of_min:.0f} %" for r in short.itertuples()) or "none",
                     "v1.0 diet above maximum": ", ".join(r.nutrient for r in over.itertuples()) or "none"})
    L += ["## 1. Cost of a nutritionally complete diet (v1.0 vs v2.0)\n\n", md_table(pd.DataFrame(rows), 2),
          "\n## 2. What the v1.0 diets were missing\n\n", md_table(pd.DataFrame(gaps)), "\n"]

    # owner detail
    prof = load_profile(PROFILES["owner"])
    res = compute(prof)
    s, _ = O.spec_from_profile(prof)
    v2 = O.solve(t, s)
    f = v2.foods[["name", "g_eaten", "g_bought", "cost_eur", "kcal_total", "protein_total", "fibre_total"]]
    L += ["## 3. Owner: complete minimum-cost day\n\n", md_table(f.reset_index(drop=True).round(1), 1),
          f"\n**€{v2.cost_eur:.2f}/day, {v2.mass_g:,.0f} g eaten.**\n\n",
          md_table(adequacy(v2, res).drop(columns=["key"]).round(1), 1), "\n"]

    # sensitivity
    sens = [("baseline", s, t)]
    for lab, mx in [("fibre max 50 g", 50), ("fibre max 80 g", 80), ("no fibre max", None)]:
        m = dict(s.micros)
        m["fibre_g"] = (m["fibre_g"][0], m["fibre_g"][1], mx)
        sens.append((lab, replace(s, micros=m), t))
    m = dict(s.micros)
    m["zinc_mg"] = (m["zinc_mg"][0], 16.3, m["zinc_mg"][2])
    sens.append(("zinc PRI at high phytate (16.3 mg)", replace(s, micros=m), t))
    m = dict(s.micros)
    m["sodium_mg"] = (m["sodium_mg"][0], None, 3000)
    sens.append(("sodium max 3,000 mg", replace(s, micros=m), t))
    m = dict(s.micros)
    m["vitamin_d_ug"] = ("Vitamin D", 15, 100)
    sens.append(("vitamin D 15 µg from food", replace(s, micros=m), t))
    m = dict(s.micros)
    m["iodine_ug"] = ("Iodine", 150, 600)
    sens.append(("iodine 150 µg from food", replace(s, micros=m), t))
    srows = []
    for lab, sp, tt in sens:
        sol = O.solve(tt, sp)
        srows.append({"variant": lab, "status": sol.status, "€/day": sol.cost_eur if sol.status == "optimal" else None,
                      "mass g": sol.mass_g if sol.status == "optimal" else None,
                      "main changes": ", ".join(sorted(set(sol.foods.name) - set(v2.foods.name))) if sol.status == "optimal"
                      else ", ".join(sol.conflicts.constraint)})
    L += ["## 4. Sensitivity (owner)\n\n", md_table(pd.DataFrame(srows), 2), "\n"]

    # typical diets
    tmpl = yaml.safe_load(open(ROOT / "config/diet_templates.yaml"))
    tt = O.food_table(roles=["core", "ingredient", "snack"])
    trows = []
    for key, d in tmpl.items():
        g = pd.Series(d["foods"], dtype=float).reindex(tt.index).fillna(0)
        tot = {k: float((tt[O.MICRO_COL.get(k, k)] * g).sum()) for k in res.micros if O.MICRO_COL.get(k, k) in tt}
        low = [f"{res.micros[k].label} {100 * v / res.micros[k].min:.0f} %" for k, v in tot.items()
               if res.micros[k].enforce and res.micros[k].min and v < res.micros[k].min * 0.99]
        high = [res.micros[k].label for k, v in tot.items() if res.micros[k].enforce and res.micros[k].max and v > res.micros[k].max * 1.01]
        trows.append({"diet": d["label"], "below minimum": ", ".join(low) or "none", "above maximum": ", ".join(high) or "none"})
    L += ["## 5. Typical diets: vitamins & minerals vs the owner's targets\n\n", md_table(pd.DataFrame(trows)), "\n",
          "## 6. Contaminants (reported only; Frida data cover ≈ 50–60 % of foods)\n\n",
          f"Owner v2.0 diet: mercury {v2.micro_totals.get('mercury_ug', 0):.1f} µg/day (TWI-based daily limit "
          f"{res.micros['mercury_ug'].max:.1f}); cadmium {v2.micro_totals.get('cadmium_ug', 0):.1f} µg/day "
          f"(limit {res.micros['cadmium_ug'].max:.1f}). Cereal- and legume-heavy diets carry most of the cadmium.\n"]
    OUT.write_text("".join(L))
    print(OUT.read_text())


if __name__ == "__main__":
    main()
